version: "3.7"

services:
  react-app:
    container_name: reactapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CUSTOM_ENV: production
    ports:
      - 7001:80
    networks:
      - ndc
  mock-server:
    container_name: mockserver
    build:
      context: ./mock-server
      dockerfile: Dockerfile
    ports:
      - 7002:5001
    networks:
      - ndc
  virtuoso:
    image: tenforce/virtuoso
    ports:
      - 8890:8890
    environment:
      - DBA_PASSWORD=myDbaPassword
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=http://www.ndc.com/test-graph
    networks:
      - ndc
  backend:
    image: ghcr.io/teamdigitale/dati-semantic-backend:20211104-42-313b969
    ports:
      - 8080:8080
    networks:
      - ndc
networks:
  ndc:
    driver: bridge
