version: "3.7"

services:
  react-app:
    container_name: reactapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CUSTOM_ENV: production
    ports:
      - 7001:80
    networks:
      - react
  mock-server:
    container_name: mockserver
    build:
      context: ./mock-server
      dockerfile: Dockerfile
    ports:
      - 7002:5001
    networks:
      - react
networks:
  react:
    driver: bridge
